### ISSUE TITLE
Slide jumps back to start of animation

### ISSUE THREAD

**Issue by dlehrich** [avinoamr/bootstrap-carousel-swipe#4]
This is working really well - however, I'm having the following problem:

When I start swiping in either direction, the slide moves under my finger as expected (so far, so good).

When I release and the slide switch takes over, the slide automatically jumps back to the beginning (so you get a jump in position).

Ideally it would carry on from where I release. Is that possible?

**Comment by jwdunn1** [comment]
I agree, the behavior is not consistent with what is expected. Furthermore, the next slide should be visible during the drag. Instead, there is only white revealed during the initial drag. Upon release, the slide jumps back (as stated) and then the next slide is revealed automatically. If this behavior is fixed, I could really use this plugin.

**Comment by avinoamr** [comment]
Thanks for letting me know. Something must've broken in one of the latest Bootstrap updates, because your requested behavior is exactly how it was originally developed. I'll appreciate pull requests to fix that, but in the meantime I moved on to using Ratchet for the same (and even better) experience.

**Comment by dlehrich** [comment]
@avinoamr are you using Ratchet side-by-side with Boostrap, or instead of it?

**Comment by avinoamr** [comment]
@dlehrich No. I switched over completely to ratchet for mobile apps

**Comment by ipalladino** [comment]
I found a temporary solution for this issue:
On **CarouselSwipe.prototye.touchend**, we can wrap all.css('left','') on a timer, this allows it to perform the animation before removing all values and resetting it to the initial one:
`
setTimeout(function(){
      all.css('left', '');
    }, 450);
`

**Comment by jakebellacera** [comment]
Just a heads up, my PR (#5) has the fix. The problem is that in Bootstrap 3.3, the `transition` property is used to animate between slides, while this lib was animating the `left` property. The demo in example.html works perfectly because it's loading in Bootstrap 3.2.
